// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ebbfydkejyavgrlvkofl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImViYmZ5ZGtlanlhdmdybHZrb2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDEwNDgsImV4cCI6MjA3MzE3NzA0OH0.wBrDTLcaWVsK_4U1ywmy7BwpKSKKvTzrhUDEX95WKMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});